### ISSUE TITLE
not a modx package

### ISSUE THREAD

**Issue by gkArvindr** [Nicola1971/OCx#3]
I downloaded the package and used the package manager in modx to install the package it throws error "looks like not a transport file: 
Nicola1971-OCx-c3465ea.zip  This file [Nicola1971-OCx-c3465ea.zip] does not appear to be a transport package
I am using MODX Revolution 2.5.1-pl

**Comment by Nicola1971** [comment]
Sorry, this is a MODx Evolution extras, you can try this beta for Revo , but does not include the OCx Module and not really tested

https://github.com/Nicola1971/OCx-Revo
